#vm: true
runtime: nodejs
env: flex

env_variables:
  # --REQUIRED--
  DATABASE_URI: mongodb://ieatmore:Eatmore123@ds121248.mlab.com:21248/ieatmore
  APP_ID: iEatMore
  MASTER_KEY: iEatMore123
  SERVER_URL: https://ieatmore-193718.appspot.com/parse
  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
  # PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:  
